In [78]:
import numpy as np;
import math

# Problem 1(a)
Centered Matrix

In [37]:
mat = np.matrix('2 2 3; 0 2 3; 1 1 3')

In [14]:
mean = mat.mean()

In [16]:
centered = mat - mean
centered

matrix([[ 0.11111111,  0.11111111,  1.11111111],
        [-1.88888889,  0.11111111,  1.11111111],
        [-0.88888889, -0.88888889,  1.11111111]])

# Problem 1(b)
Covariance Matrix

In [22]:
cov = np.cov(centered)
cov

array([[0.33333333, 0.66666667, 0.66666667],
       [0.66666667, 2.33333333, 1.33333333],
       [0.66666667, 1.33333333, 1.33333333]])

# Problem 1(c)
Compute the principle components of X. Computing SVD shows that it's the same as the eigen decomp since U = V = Q

In [67]:
np.linalg.svd(cov)

(array([[-2.79603668e-01,  3.49029782e-01, -8.94427191e-01],
        [-7.80454320e-01, -6.25212808e-01,  5.55111512e-17],
        [-5.59207335e-01,  6.98059565e-01,  4.47213595e-01]]),
 array([3.52752523e+00, 4.72474768e-01, 1.26533209e-16]),
 array([[-2.79603668e-01, -7.80454320e-01, -5.59207335e-01],
        [ 3.49029782e-01, -6.25212808e-01,  6.98059565e-01],
        [ 8.94427191e-01, -1.06540163e-16, -4.47213595e-01]]))

In [68]:
np.linalg.eig(cov)

(array([3.52752523e+00, 1.11967988e-16, 4.72474768e-01]),
 array([[-2.79603668e-01, -8.94427191e-01,  3.49029782e-01],
        [-7.80454320e-01, -2.15178894e-20, -6.25212808e-01],
        [-5.59207335e-01,  4.47213595e-01,  6.98059565e-01]]))

The first principle component is (-2.8, -7.8, -5.6), the second is (3.5, -6.3, 7) and the third is (-9, -2.1, 4.4).

# Problem 1(d)
## Compute distance matrix

In [60]:
D=np.matrix("0 0 0; 0 0 0; 0 0 0")
for i in range(0,3):
    for j in range(0,3):
        #print("i"+str(i)+" j"+str(j))
        #print(np.linalg.norm(mat[i] - mat[j]))
        D[i,j] = np.linalg.norm(mat[i] - mat[j])
        # square the distances
        D[i,j] = D[i,j] ** 2
D

matrix([[0, 4, 1],
        [4, 0, 1],
        [1, 1, 0]])

## Compute centering matrix

In [61]:
I = np.matrix("1 0 0; 0 1 0; 0 0 1");
J = np.matrix("1 1 1; 1 1 1; 1 1 1");
C = I - J/3
C

matrix([[ 0.66666667, -0.33333333, -0.33333333],
        [-0.33333333,  0.66666667, -0.33333333],
        [-0.33333333, -0.33333333,  0.66666667]])

## Center distance matrix

In [65]:
B = (-1/2)*C*D*C
B

matrix([[ 1.00000000e+00, -1.00000000e+00,  6.16790569e-18],
        [-1.00000000e+00,  1.00000000e+00,  6.16790569e-18],
        [ 3.39234813e-17,  2.00456935e-17,  8.01827740e-17]])

In [98]:
(evalues, evecs) = np.linalg.eig(B)
print(evalues)
print(evecs)
#evalues = numpy.sort(evalues)

[2.0000000e+00 0.0000000e+00 8.0182774e-17]
[[ 7.07106781e-01 -7.07106781e-01  7.64719113e-02]
 [-7.07106781e-01 -7.07106781e-01  7.64719113e-02]
 [ 2.39875237e-17  2.39875237e-17  9.94134847e-01]]


In [99]:
# Create the diagonal part of the matrix
V = np.matrix([
    [math.sqrt(evalues[0]), 0, 0],
    [0, math.sqrt(evalues[2]), 0],
    [0, 0, math.sqrt(evalues[1])]
])
print(V)

# reorder the eigenvectors
evecs = evecs * np.matrix("1 0 0; 0 0 1; 0 1 0")

[[1.41421356e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.95448346e-09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]


In [100]:
# Square root the eigenvalues, place them on a diagonal, then multiply by their eigenvectors
X = V * evecs
X

matrix([[ 1.00000000e+00,  1.08147614e-01, -1.00000000e+00],
        [-6.33177598e-09,  6.84766465e-10, -6.33177598e-09],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [ ]:
# Now embed the rows of X in R^2 with the above X
